BOT_ID = 'XXXXXXXX'
OFFICIALS_CHAT_ID = 'XXXXXXXX'
WEATHER_KEY = 'XXXXXXXX'
PUBLIC_CHAT_ID = 'XXXXXXXX'

TWILIO_ACC_SID = 'XXXXXXXX'
TWILIO_AUTH_TOKEN = 'XXXXXXXX'
TWILIO_SERVICE_SID = 'XXXXXXXX'

MAILGUN_API_KEY= 'XXXXXXXX-XXXXXXXX'
MAILGUN_DOMAIN = 'XXXXXXXX.XXXXXXXX.XXXXXXXX'

TWITTER_CONSUMER_KEY = 'XXXXXXXX'
TWITTER_CONSUMER_SECRET = 'XXXXXXXX'
TWITTER_ACCESS_TOKEN = 'XXXXXXXX'
TWITTER_ACCESS_TOKEN_SECRET = 'XXXXXXXX'
